name: "Application Image Development CI"
on:
  push:
    branches:
    - development
    paths:
    - app/**
  pull_request:
    paths:
    - app/**
jobs:
  image_ci:
    name: "Application Image CI"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      uses: docker/build-push-action@v2
      with:
        context: app
        platforms: linux/amd64
        push: false
        tags: |
          go-counter-online:ci