name: "Container Image CI/CD"
on: workflow_dispatch
  # push:
  #   branches:
  #   - master
  #   paths:
  #   - app/**
  # pull_request:
  #   paths:
  #   - app/**
jobs:
  image_cicd:
    name: "Container Image CI/CD"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to ECR Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ${{ secrets.AWS_ECR_API_ENDPOINT }}
        username: 'AWS'
        password: ${{ secrets.AWS_ECR_API_PASSWORD }}
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: app
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.AWS_ECR_API_IMAGE_NAME }}:latest
          ${{ secrets.AWS_ECR_API_IMAGE_NAME }}:${{ steps.vars.outputs.sha_short }}
    - name: Update image name
      id: updateImageName
      uses: mikefarah/yq@v4.18.1
      with:
        cmd: yq -i '.images[0].newName = "${{ secrets.AWS_ECR_API_IMAGE_NAME }}"' 'deployments/kustomize/api/overlay/prd/kustomization.yaml'
    - name: Update image tag
      id: updateImageTag
      uses: mikefarah/yq@v4.18.1
      with:
        cmd: yq -i '.images[0].newTag = "${{ steps.vars.outputs.sha_short }}"' 'deployments/kustomize/api/overlay/prd/kustomization.yaml'
    - name: Commit image changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'fix(cd): Automated Change (update kustomization image tag)'
        file_pattern: deployments/kustomize/api/overlay/prd/kustomization.yaml