name: "Kubernetes CD"
on: workflow_dispatch
  # push:
  #   branches:
  #   - master
  #   paths:
  #   - app/**
  # pull_request:
  #   paths:
  #   - app/**
jobs:
  docker_ci_cd:
    name: "Kubernetes CD"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
    - name: Configure kubeconfig
      run: |
        aws eks update-kubeconfig --name prd-go-counter-online-eks
    - name: Register kubeconfig
      id: kubeconfig
      run: |
        echo "::set-output name=KUBECONFIG::$(cat $HOME/.kube/config | base64 -w0)"
    - name: Test
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ steps.kubeconfig.outputs.KUBECONFIG }}
        version: v1.21.0
        command: get nodes -owide